// <auto-generated />
namespace AuthService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class restri0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(restri0));
        
        string IMigrationMetadata.Id
        {
            get { return "201612170231218_restri0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
