// <auto-generated />
namespace AuthService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class restri0000 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(restri0000));
        
        string IMigrationMetadata.Id
        {
            get { return "201612210254404_restri0000"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
