// <auto-generated />
namespace TransactionService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class related_postransaction_to_paymentofmethod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(related_postransaction_to_paymentofmethod));
        
        string IMigrationMetadata.Id
        {
            get { return "201610200413401_related_postransaction_to_paymentofmethod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
