// <auto-generated />
namespace TransactionService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class transaction__related_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transaction__related_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201610151335486_transaction__related_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
