// <auto-generated />
namespace AdminService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_Children_Property_From_PeopleDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_Children_Property_From_PeopleDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201609260745532_remove_Children_Property_From_PeopleDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
