// <auto-generated />
namespace AdminService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class make_ItemId_In_PosItem_table_not_generatedByDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(make_ItemId_In_PosItem_table_not_generatedByDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201609271417470_make_ItemId_In_PosItem_table_not_generatedByDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
