// <auto-generated />
namespace AdminService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_PosItemDetail_for_simplify_only_for_demo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_PosItemDetail_for_simplify_only_for_demo));
        
        string IMigrationMetadata.Id
        {
            get { return "201609271402464_remove_PosItemDetail_for_simplify_only_for_demo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
