// <auto-generated />
namespace AdminService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_DateToDeactivate_column_for_PosItemModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_DateToDeactivate_column_for_PosItemModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201609280113158_add_DateToDeactivate_column_for_PosItemModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
