// <auto-generated />
namespace AdminService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class update3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update3));
        
        string IMigrationMetadata.Id
        {
            get { return "201610231420183_update3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
