// <auto-generated />
namespace AdminService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_People_Model_which_for_demo_purpose_And_Add_Some_other_models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_People_Model_which_for_demo_purpose_And_Add_Some_other_models));
        
        string IMigrationMetadata.Id
        {
            get { return "201609270805202_remove_People_Model_which_for_demo_purpose_And_Add_Some_other_models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
