// <auto-generated />
namespace AdminService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rename_a_column_from_versioning_to_snapshot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_a_column_from_versioning_to_snapshot));
        
        string IMigrationMetadata.Id
        {
            get { return "201609280109597_rename_a_column_from_versioning_to_snapshot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
